## This is for DEV. It runs the Dockerfile with hot reloading
## After changing dependencies (package.json / bun.lock) run:
##   docker compose down -v && docker compose up --build

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - app_data:/app/data

    # ENABLE HOT RELOADING
    command: bun --hot src/index.ts

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=development
      - PROXY_DATACENTER
      - PROXY_RESIDENTIAL

volumes:
  app_data:
